In [1]:
#подгружаем необходимые библиотеки
import pandas as pd
import numpy as np

In [9]:
#считываем датасет с населением
eupop=pd.read_csv('EUpop.csv')
europe=np.array(['Belgium', 'Germany', 'Estonia', 'Finland', 'United Kingdom',
'Guernsey', 'Jersey', 'Isle of Man', 'Netherlands', 'Ireland',
'Denmark', 'Luxembourg', 'Norway', 'Poland', 'Sweden', 'Spain',
'Albania', 'Bulgaria', 'Cyprus', 'Croatia', 'France', 'Greece',
'Hungary', 'Italy', 'Slovenia', 'Czech Republic', 'Malta',
'Austria', 'Portugal', 'Bosnia and Herzegovina', 'Romania',
'Switzerland', 'Turkey', 'Moldova', 'Macedonia', 'Gibraltar',
'Serbia', 'Montenegro', 'Slovakia', 'Ukraine', 'Russia', 'Belarus',
'Latvia', 'Lithuania','Faroe Islands', 'Greenland', 'Iceland'])

In [46]:
europe_df=eupop[eupop['Country or Area'].isin(europe)]
europe_new=europe_df.drop(['Value Footnotes', 'Source Year', 'Record Type', 'Sex', 'Reliability', 'Area'], axis=1)
europe_new.to_csv('Data.csv')
europe_new

     Country or Area  Year        Value
0            Albania  2017  2876591.000
1            Albania  2017  2873458.000
2            Albania  2016  2886026.000
3            Albania  2016  2876101.000
4            Albania  2015  2892303.000
5            Albania  2015  2880703.000
6            Albania  2014  2895947.000
7            Albania  2014  2889104.000
8            Albania  2013  2895092.000
9            Albania  2012  2900401.000
10           Albania  2011  2800138.000
11           Albania  2011  2904780.000
12           Albania  2010  2913021.000
13           Albania  2009  2927519.000
14           Albania  2008  2947314.000
15           Albania  2007  2970017.000
16           Albania  2006  2992547.000
17           Albania  2005  3011487.000
18           Albania  2004  3026939.000
19           Albania  2003  3039616.000
20           Albania  2002  3051010.000
21           Albania  2001  3069275.000
22           Albania  2001  3060173.000
23           Albania  2000  3060907.500
24           Albania  1999  3053830.752
25           Albania  1998  3055331.182
26           Albania  1997  3074831.916
27           Albania  1996  3075545.172
28           Albania  1995  3050011.687
29           Albania  1994  3035180.500
...              ...   ...          ...
3481     Switzerland  1973  6310200.000
3482     Switzerland  1972  6288168.000
3483     Switzerland  1972  6253300.000
3484     Switzerland  1971  6233744.000
3485     Switzerland  1970  6269783.000
3486     Switzerland  1970  6193064.000
3487     Switzerland  1969  6136389.000
3488     Switzerland  1968  6067712.000
3489     Switzerland  1967  5991783.000
3490     Switzerland  1966  5917996.000
3491     Switzerland  1965  5856472.000
3492     Switzerland  1964  5789225.000
3493     Switzerland  1963  5694241.000
3494     Switzerland  1962  5573810.000
3495     Switzerland  1961  5434300.000
3496     Switzerland  1960  5429061.000
3497     Switzerland  1960  5327822.000
3498     Switzerland  1959  5259000.000
3499     Switzerland  1958  5199000.000
3500     Switzerland  1957  5126000.000
3501     Switzerland  1956  5045000.000
3502     Switzerland  1955  4980000.000
3503     Switzerland  1954  4929000.000
3504     Switzerland  1953  4878000.000
3505     Switzerland  1952  4815000.000
3506     Switzerland  1951  4749000.000
3507     Switzerland  1950  4714992.000
3508     Switzerland  1950  4694000.000
3509     Switzerland  1949  4639000.000
3510     Switzerland  1948  4608000.000

[3271 rows x 3 columns]